dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  # system is == 4.02.3
  - COMPILER="system"
  # Main test targets
  matrix:
  - MC_VERSION="1.6.4"

install:
- mkdir -p ~/opam/
- opam init -j ${NJOBS} --root=~/opam/${COMPILER}-{$MC_VERSION} --compiler=${COMPILER} -n -y
- eval $(opam config --root=~/opam/${COMPILER}-{$MC_VERSION} env)
- opam config var root
- opam repo add coq-released http://coq.inria.fr/opam/released
- opam install -j ${NJOBS} -y coq-math-comp.${MC_VERSION}
- opam list

script:
- eval $(opam config --root=~/opam/${COMPILER}-{$MC_VERSION} env)
- make -j ${NJOBS}
