dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  # system is == 4.02.3
  matrix:
  - COMPILER="system" MC_VERSION="dev" COQ_VERSION="8.7.2"

jobs:
  include:
    - stage: opam
      script:
      - mkdir -p ~/opam/
      - rm -rf ~/opam/${COMPILER}-{$MC_VERSION}
      - opam init -j ${NJOBS} --root=~/opam/${COMPILER}-{$MC_VERSION} --compiler=${COMPILER} -n -y
      - eval $(opam config --root=~/opam/${COMPILER}-{$MC_VERSION} env)
      - opam repo add coq-released http://coq.inria.fr/opam/released
      - opam repo add coq-released http://coq.inria.fr/opam/extra-dev
    - stage: coq
      script:
      - eval $(opam config --root=~/opam/${COMPILER}-{$MC_VERSION} env)
      - opam install -j ${NJOBS} -v -y coq.${COQ_VERSION}
      - opam pin add coq ${COQ_VERSION}
    - stage: math-comp
      script:
      - eval $(opam config --root=~/opam/${COMPILER}-{$MC_VERSION} env)
      - opam install -j ${NJOBS} -v -y coq-mathcomp-character.${MC_VERSION}
      - opam pin add coq-mathcomp-character ${MC_VERSION}
    - stage: odd-order
      script:
      - eval $(opam config --root=~/opam/${COMPILER}-{$MC_VERSION} env)
      - make -j ${NJOBS}
